### ISSUE TITLE
Getting started: Errors

### ISSUE THREAD

**Issue by SoxFace** [atomicjolt/lti_starter_app#1]
Hi there, 

Setting up this repo and I hit a few errors. Thought I'd share them here for good measure as they were quick and easy fixes.

**Error 1**
`undefined method `for' for #<Devise::ParameterSanitizer:0x007fecfeb4bef8>`

so I changed 'for' to 'permit' in registrations_controller.rb based on [this suggestion](http://stackoverflow.com/questions/37341967/rails-5-undefined-method-for-for-devise-on-line-devise-parameter-sanitizer) which worked.

**Error 2**
`NameError - undefined local variable or method `new_canvas_authentication_path' for #<#<Class:0x007fcc624046e8>:0x007fcc69eac0d0>
Did you mean?  new_admin_canvas_authentication_path:`

so I added 'admin' to the _links.html.erb which worked.

**Newbie Error: Email confirmation**
Got the app up and running and when signing up, I didn't receive an email. It took me a few minutes til I found it in the terminal #newbie. Then I just copied the href into the browser to confirm the account #bingo

`Devise::Mailer#confirmation_instructions: processed outbound mail in 247.2ms

Sent mail to sonya.corcoran@uts.edu.au (9.1ms)
Date: Fri, 04 Nov 2016 13:05:05 +1100
From: admin@example.com
Reply-To: admin@example.com
To: sonya.corcoran@uts.edu.au
Message-ID: <581becd152c99_33c43fe630c3fa04122d@VCGMLB014B00011.local.mail>
Subject: Confirmation instructions
Mime-Version: 1.0
Content-Type: text/html;
 charset=UTF-8
Content-Transfer-Encoding: 7bit

<p>Welcome sonya.corcoran@uts.edu.au!</p>

<p>You can confirm your account email through the link below:</p>

<p><a href="http://localhost:3000/users/confirmation?confirmation_token=g-XXXXXXXXXXXXX">Confirm my account</a></p>`

**Error 3**
When signing out:

`ActionController::RoutingError at /users/sign_out
uninitialized constant UsersController`

Still working on this one and will update once I've worked it out.

**Comment by jbasdf** [comment]
Error #1 should be fixed in the latest version:
https://github.com/atomicjolt/lti_starter_app/blob/master/app/controllers/registrations_controller.rb

Error #2 should be fixed as we've removed new_canvas_authentication_path from _links.html.erb

I believe the default configuration is for the app to not send email in developer mode. You can change it in developer.rb by setting the following to true:
config.action_mailer.perform_deliveries = false

You'll also need to configure a mail server.

Error 3 should also be fixed. Use "destroy_user_session_url" to generate the url. Note that we've configured Devise so that it will use a 'get' instead of a 'delete' to sign the user out. We did that so that the client app could easily display a sign out link for the user.
