### ISSUE TITLE
RuntimeError (Please specify a valid oauth_consumer_key or valid domain name for this request):

### ISSUE THREAD

**Issue by SoxFace** [atomicjolt/lti_starter_app#19]
Hi AJers, 

I've just spun up a new lti-starter-app with the latest changes.

I was getting `RuntimeError (Please specify a valid oauth_consumer_key or valid domain name for this request):` until I swapped out the following in apartment.rb and it's back working.

```
THIS IS NOT WORKING IN LATEST REPO
Rails.application.config.middleware.insert_before "Warden::Manager", "Apartment::Elevators::Generic", lambda { |request|
  key = request.params["oauth_consumer_key"]
  host = request.host_with_port
  if application_instance = ApplicationInstance.find_by(lti_key: key) || ApplicationInstance.find_by(domain: host)
    application_instance.tenant
  else
    raise "Please specify a valid oauth_consumer_key or valid domain name for this request"
  end
}

THIS IS WORKING FROM PREVIOUS REPO
Rails.application.config.middleware.insert_before 'Warden::Manager', 'Apartment::Elevators::Generic', lambda { |request|
  if lti_key = request.params["oauth_consumer_key"]
    ApplicationInstance.find_by(lti_key: lti_key).try(:lti_key)
  end
}
```

I'm also getting a couple of warnings but I think the first is a known issue with OmniAuth:

`WARN -- : You are setting a key that conflicts with a built-in method OmniAuth::AuthHash::InfoHash#name defined at /Users/131432/.rvm/gems/ruby-2.3.1@SocialWidgets/gems/omniauth-1.3.2/lib/omniauth/auth_hash.rb:34. This can cause unexpected behavior when accessing the key via as a property. You can still access the key via the #[] method.`

`/gems/lms-api-1.2.4/lib/lms/canvas_urls.rb:498: warning: key "PEER_REVIEWS_CREATE_PEER_REVIEW_COURSES" is duplicated and overwritten on line 500`

Am I okay to continue using the previous Warden_Manager? It won't blow anything up?

Cheers
Sonya

**Comment by jbasdf** [comment]
The exception in the apartment.rb file is a new addition. Every LTI tool must be identified by either the lti key or a domain so that apartment can correctly identify which tenant to switch to. The absence of one of those two value needs to raise an exception or else the data from different LTI tools could be mixed into the same data schema. Once that happens it will be nearly impossible to separate out the data. The way to fix the problem is to be sure to configure your seeds file with the proper lti key and domain for each application instance and then to be sure to access the tool using either the matching domain or to launch it via LTI using the chosen key.

I'm unsure about Warden_Manager versions. Why do you need to use an older one?
